GitHubExplorer.Web/Models/GitHubProfileModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using GitHubExplorer.BusinessLayer.Model;

namespace GitHubExplorer.Web.Models
{
    public class GitHubProfileModel
    {
        public GitHubProfileModel()
        {
            this.GitHubRepositories = new List<GitHubRepository>();
        }

        [Required]
        public string UserName { get; set; }
        public string Location { get; set; }
        public string AvatarUrl { get; set; }

        public IList<GitHubRepository> GitHubRepositories { get; set; } 
    }
}

GitHubExplorer.Web/Controllers/GitHubController.cs
using System.Web.Mvc;
using GitHubExplorer.Abstractions;
using GitHubExplorer.BusinessLayer.Model;
using GitHubExplorer.Web.Models;

namespace GitHubExplorer.Web.Controllers
{
    public class GitHubController : Controller
    {
        public readonly IVcsService<GitHubUser, GitHubRepository> _ivcsService;

        public GitHubController(IVcsService<GitHubUser, GitHubRepository> ivcsService)
        {
            _ivcsService = ivcsService;
        }

        // GET: GitHub
        [HttpGet]
        public ActionResult SearchUser()
        {
            return View(new GitHubProfileModel());
        }

        [HttpPost]
        public ActionResult SearchUser(GitHubProfileModel model)
        {
            var gitHubUser = _ivcsService.GetUser(model.UserName);
            model.AvatarUrl = gitHubUser.AvatarUrl;
            model.Location = gitHubUser.Location;
            model.GitHubRepositories = gitHubUser.GitHubRepositories;
            return View(model);
        }
    }
}

GitHubExplorer.Web/Views/GitHub/SearchUser.cshtml
@model GitHubExplorer.Web.Models.GitHubProfileModel
@{
    ViewBag.Title = "Search User";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Search User</h2>
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("SearchUser", "GitHub"))
        {
            <div class="form-group">
                @Html.TextBoxFor(x => x.UserName)      
            </div>
            <span class="form-group">
                <button class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search</button>
            </span>
            <div>
                @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
            </div>
        }
    </div>
</div>
@if (!string.IsNullOrEmpty(Model.AvatarUrl))
{
    <hr />
    <div class="row">
        <div class="col-md-4">
            <h1>
                @Model.UserName
            </h1>
            <p>
                <img src="@Model.AvatarUrl" alt="@Model.UserName" />
            </p>
            <p>@Model.Location</p>
            <h3>Top 5 repositories</h3>
            <ul>
                @foreach (var repo in Model.GitHubRepositories)
                {
                    <li><a target="_blank" href="@repo.RepositoryUrl">@repo.RepositoryName (<span class="glyphicon glyphicon-star"></span> : @repo.StarCount)</a></li>
                }
            </ul>
        </div>
    </div>
}

GitHubExplorer.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="/dist/all.min.css"/>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header bar-color">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GitHub Explorer", "SearchUser", "GitHub", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Spyros Desyllas, ver.@ViewContext.Controller.GetType().Assembly.GetName().Version.ToString(3)</p>
        </footer>
    </div>
    
    <script src="/dist/all.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>